const router = require('express-promise-router')();
const swaggerUI = require('swagger-ui-express');
const swaggerDoc = require('./swagger_output.json');
const options = {disableLogs: true};
const swaggerAutogen = require('swagger-autogen')(options);

const doc = {
    info: {
        title: 'API Documentation for Food Ordering System',
        description: 'This is a REST API application made with Express. It retrieves data from a MongoDB database and returns it as JSON.',
        version: '1.0.0',
    },
    host: 'localhost:3001',
    schemes: ['http', 'https'],
    securityDefinitions: {
        Bearer: {
            type: "apiKey",
            name: "Authorization",
            in: "header",
            description: "For accessing the API a valid JWT token must be passed in all the queries in the 'Authorization' header.\n\nA valid JWT token is generated by the API and retured as answer of a call to the route /user/login giving a valid user & password. The following syntax must be used in the 'Authorization' header :\n\nBearer xxxxxx.yyyyyyy.zzzzzz"
        }
    },
    security: [{
        Bearer: []
    }]
};

const outputFile = './app/routes/swagger/swagger_output.json';
const endpointsFiles = ['app/routes/mainRouter.js'];

//swaggerAutogen(outputFile, endpointsFiles, doc);

router.use('/', swaggerUI.serve, swaggerUI.setup(swaggerDoc));

module.exports = {Swagger_Router: router};