# Docker compose file
services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  app:
    image: 038462760519.dkr.ecr.us-east-1.amazonaws.com/webapp:latest
    container_name: webapp
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_URL: redis://redis:6379
      PORT: 3000
      SWAGGER_URL: 'http://ec2-54-226-17-230.compute-1.amazonaws.com'
    ports:
      - "3000:3000"
