name: CI/CD Pipeline for Node.js

on:
  push:
    branches:
      - main  # Runs the pipeline when code is pushed to the main branch
  pull_request:
    branches:
      - main  # Runs the pipeline on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # The pipeline will run on the latest Ubuntu runner

    strategy:
      matrix:
        node-version: [16.x, 18.x]  # Use Node.js 16.x or higher

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Check out the code from the repository

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}  # Use Node.js version from matrix

      - name: Install dependencies
        run: npm install  # Install project dependencies

      - name: Run tests
        run: npm test  # Run the test suite defined in package.json

      - name: Build the project
        run: npm run build  # Optional: build step if your project needs one

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}  # Use a secret for the Heroku API key
        run: |
          git remote add heroku https://git.heroku.com/YOUR-HEROKU-APP-NAME.git
          git push heroku main
